- type: gameMap
  id: Train
  mapName: 'Train'
  mapPath: /Maps/train.yml
  maxRandomOffset: 0
  randomRotation: false
  # Corvax-start
  minPlayers: 20
  maxPlayers: 50
  # Corvax-end
  stations:
    Train:
      stationProto: StandardNanotrasenStation
      components:
        - type: StationNameSetup
          mapNameTemplate: 'Train "Sentipode" {0}-{1}'
          nameGenerator:
            !type:NanotrasenNameGenerator
            prefixCreator: 'ED'
        - type: StationEmergencyShuttle
          emergencyShuttlePath: /Maps/Shuttles/emergency_omega.yml # TODO - add railway station
        - type: StationJobs
          availableJobs:
            #service
            ADTBlueShieldOfficer: [ 1, 1 ] #ADT-Roles
            Captain: [ 1, 1 ]
            IAA: [ 1, 1 ]
            HeadOfPersonnel: [ 1, 1 ]
            Bartender: [ 1, 1 ]
            Botanist: [ 2, 2 ]
            Chef: [ 1, 1 ]
            Janitor: [ 2, 2 ]
            Chaplain: [ 1, 1 ]
            Librarian: [ 1, 1 ]
            ServiceWorker: [ 2, 3 ]
            Detective: [ 1, 1 ]
            #engineering
            ChiefEngineer: [ 1, 1 ]
            SeniorEngineer: [ 1, 1 ]
            AtmosphericTechnician: [ 2, 2 ]
            StationEngineer: [ 4, 4 ]
            TechnicalAssistant: [ 3, 3 ]
            #medical
            ChiefMedicalOfficer: [ 1, 1 ]
            SeniorPhysician: [ 1, 1 ]
            Chemist: [ 2, 2 ]
            MedicalDoctor: [ 2, 2 ]
            MedicalIntern: [ 2, 2 ]
            Paramedic: [ 1, 1 ]
            #science
            ResearchDirector: [ 1, 1 ]
            SeniorResearcher: [ 1, 1 ]
            Scientist: [ 4, 4 ]
            ResearchAssistant: [ 2, 2 ]
            #security
            HeadOfSecurity: [ 1, 1 ]
            Warden: [ 1, 1 ]
            WardenHelper: [ 1, 1 ]
            SeniorOfficer: [ 1, 1 ]
            ecurityOfficer: [ 6, 6 ]
            SecurityCadet: [ 3, 3 ]
            Brigmedic: [ 1, 1 ]
            #Lawyer: [ 1, 2 ] # Corvax-IAA
            #supply
            Quartermaster: [ 1, 1 ]
            SalvageSpecialist: [ 5, 5 ]
            CargoTechnician: [ 3, 3 ]
            SeniorSalvageSpecialist: [ 1, 1 ]
            #civilian
            Passenger: [ 1, 1 ]
            Clown: [ 1, 1 ]
            Mime: [ 1, 1 ]
            Musician: [ 1, 1 ]
            Borg: [ 3, 3 ]
            Reporter: [ 1, 1 ]

        # Corvax-next blob-config-start SMALL+
        - type: StationBlobConfig
          stageBegin: 40
          stageCritical: 500
          stageTheEnd: 900
        # Corvax-next blob-config-end
