- type: guideEntry
  id: Security
  name: guide-entry-security
  text: "/ServerInfo/_Mini/Security/Security.xml"
  children:
  - Forensics
  - Defusal
  - CriminalRecords
# - CorporateLaw # Corvax-Corporate-Law

- type: guideEntry
  id: Forensics
  name: guide-entry-forensics
  text: "/ServerInfo/_Mini/Security/Forensics.xml"

- type: guideEntry
  id: Defusal
  name: guide-entry-defusal
  text: "/ServerInfo/_Mini/Security/Defusal.xml"

- type: guideEntry
  id: CriminalRecords
  name: guide-entry-criminal-records
  text: "/ServerInfo/_Mini/Security/CriminalRecords.xml"

# nah thanks we dont need that
# - type: guideEntry
#   id: SpaceLaw
#   name: guide-entry-rules-space-law
#   text: "/ServerInfo/_Mini/ServerRules/SpaceLaw/SpaceLaw.xml"
#   children:
#   - SpaceLawCrimeList

# - type: guideEntry
#   id: SpaceLawCrimeList
#   name: guide-entry-rules-sl-crime-list
#   text: "/ServerInfo/_Mini/ServerRules/SpaceLaw/SLCrimeList.xml"
