- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 7200
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 7200
  startingGear: BrigmedicGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
    - Brig
    - Detective
    - External
    - Medical
    - Security
    - Maintenance
    - Service
    - Chemistry
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: SurgerySpeedModifier
      speedModifier: 1.75
    - type: Skills # Corvax-Next-Skills
      skills:
      - Shooting
      - Surgery
      - MedicalEquipment
      - Butchering

- type: startingGear
  id: BrigmedicGear
  equipment:
    shoes: ClothingShoesBootsJackSecFilled
    gloves: ClothingHandsGlovesNitrile
    eyes: ClothingEyesHudMedSec
    id: BrigmedicPDA
    ears: ClothingHeadsetBrigmedic
    belt: ClothingBeltMedicalFilled
    pocket1: WeaponDisabler
  storage:
    back:
    - MedkitCombatFilled
    - ClothingNeckSecBadgeBrigmedic # Corvax-Next-Badges
    - DefibrillatorCompact
    - LauncherSyringe
    - BoxBrigmedic
    - ChemistryBottlePax
