- type: job
  id: SeniorSalvageSpecialist
  name: Ведущий утилизатор
  description: Главный любитель работки и мудрый наставник раздолбаев-утилей.
  playTimeTracker: JobSeniorSalvageSpecialist
  requirements:
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 14400 # 4 hours
    - !type:AgeRequirement
      requiredAge: 24
  startingGear: SeniorSalvageSpecialistGear
  icon: "JobIconSeniorSalvageSpecialist"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External
  - SeniorSalvage

- type: startingGear
  id: SeniorSalvageSpecialistGear
  equipment:
    id: SeniorSalvagePDA
    ears: ClothingHeadsetMining
    neck: ClothingNeckCloakMiner
    back: ClothingBackpackSeniorSalvage
#  storage:
#    back:
#    - RubberStampSeniorSalvage
